title: Hot Mess Express
author: Andrea Castillo
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My English professor had us write a Thought Journal that acted like a "stream of consciousness" about the movies we watched in class. After reading my Hot Mess of a journal, he said that I should write a book. So instead, I made a website.

# social links
twitter_username: @castiyeaux
github_username:  @castiyeaux

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
